[package]
name = "rust_mysql_web_service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-rt = "2"
mysql = "23"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }